# This is the WBAF config file, do not change version id.
version: 1
enable-auto-fill: true
padding-distance: 208
enabled-worlds:
  - world
server-start-delay: 180
player-quit-delay: 600
fill-speed: 20