name: WBAutoFill
version: 1.2
depend: [WorldBorder]
main: cat.kiwi.minecraft.wbautofill.WBAutoFillPlugin

commands:
  wbaf:
    description: World Border Auto Fill
    usage: /wbaf help
    permission: worldborderautofill.admin
  worldborderautofill:
    description: World Border Auto Fill
    usage: /wbaf help
    permission: worldborderautofill.admin